services:
  toolkit:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/home/sagemaker-user:cached
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: sleep infinity
    # command: sleep infinity
volumes:
    bashhistory:
